### PR TITLE
Remove hyperlinks from recipe descriptions

### LINKED ISSUE #240: Description HTML Links
**Description**
The links in the description of the recipes are broken. Remove the links with string parsing.

**Issue Points**: 1

### PR DESCRIPTION
**Pull request by P0keDev**
Resolves #240 

**Description**

Deletes all anchor tags present in the recipe object's description, while leaving the rest of the text intact. This may make some descriptions a bit confusing or unnecessarily wordy, but fancier string manipulation is probably not worth pursuing.

### CODE REVIEW

**Review by keli214 — APPROVED** [review]

File: source/components/recipe-page.js [hunk 1]
```diff
@@ -114,7 +116,7 @@ export class RecipePage extends HTMLElement {
 
     shadow.getElementById("recipe-image").src = recipeObj.image;
     shadow.getElementById("recipe-description").innerHTML =
-      recipeObj.description;
+      recipeObj.description.replace(ANCHOR_REGEX, ""); // remove links
```
Comment (minhdinh901) [inline source/components/recipe-page.js:119]: We should also store this new description in the recipe page's recipe object, this is to make the removed link tags not show up when editing the recipe description
```
      let modifiedDescription = recipeObj.description.replace(ANCHOR_REGEX, ""); // remove links
      shadow.getElementById("recipe-description").innerHTML = modifiedDescription;
      this.recipe.description = modifiedDescription;
```

**Review by minhdinh901 — APPROVED** [review]
